apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-redis-reservation
  description: Python library for resource reservation using Redis
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
